changing package-lock file(dredd removed).
Signed-off-by: Sophia Garg <sofigarg@amazon.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,17 +9,20 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Set up Node.js 
-      uses: actions/setup-node@v1   
+      uses: actions/setup-node@v2   
 
     - name: Installing node modules
       run: npm install
       working-directory: ./test 
 
-    - name: checking dredd version
-      run: |
-        npx dredd --version
-        npm list
-      working-directory: ./test   
+    - name: Installing Dredd
+      run: sudo npm install dredd --global --unsafe-perm=true --allow-root      
+
+    # - name: checking dredd version
+    #   run: |
+    #     npx dredd --version
+    #     npm list
+    #   working-directory: ./test   
 
     - name: Set up Python
       uses: actions/setup-python@v2
@@ -37,7 +40,25 @@ jobs:
       working-directory: ./test  
 
     - name: Waiting for OpenSearch domain to be up.
-      run: sh ./.github/workflows/domain-check.sh
+      run: |
+        counter=1
+        for counter in {1..10}
+        do
+            if [ $(curl -s -o /dev/null --head -w "%{http_code}" 'https://admin:admin@localhost:9200' -H 'Content-Type:application/json' --insecure -v) -ne 200 ]; then
+                sleep 30s
+            else
+                # Waiting for security plugin to be initialised and become operational.
+                echo  "Waiting for addtional 30 seconds.. for Opensearch domain to be up."
+                sleep 30s
+                break 
+            fi  
+        done
+        if [ $counter -eq 11 ]; then
+            echo "Unable to connect with OpenSearch URL https://localhost:9200/"
+            exit 1
+        fi
+      shell: bash
+      working-directory: ./test 
     
     - name: Run script file
       run: |
